// This file is automatically generated by VS Code
// Please do not modify it manually. All changes will be lost.
var React = require('/Users/gabriel/Documents/Code/bookly/node_modules/react');
var { Component } = React;
var ReactNative = require('/Users/gabriel/Documents/Code/bookly/node_modules/react-native');
var { AppRegistry } = ReactNative;
AppRegistry.registerRunnable('main', function(appParameters) {
    AppRegistry.runApplication('bookly', appParameters);
});
require('/Users/gabriel/Documents/Code/bookly/index.android.js');